config/routes.rb
Rails.application.routes.draw do
  #home
  root to: 'gossips#index'

  #pages menu
  get '/team', to: 'pages#team'
  get '/contact', to: 'pages#contact'
  get '/register', to: 'pages#create'
  #gossips
  resources :gossips do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  #users
  resources:users

  #cities
  resources:cities, only: [:show]

  #session
  resources:sessions


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users 
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title,
    presence: true,
    length: { minimum: 3, too_short: "%{count} characters is the minimum allowed", maximum: 14, too_long: "%{count} characters is the maximum allowed" }
  validates :content,
    presence: true
  belongs_to :user
  has_many :join_table_tag_gossips
  has_many :tags, through: :join_table_tag_gossips
  has_many :comments
  has_many :users, through: :comments
end

app/models/join_pm_receiver.rb
class JoinPmReceiver < ApplicationRecord
  belongs_to :private_message
  belongs_to :recipient, class_name: "User"
end

app/models/join_table_tag_gossip.rb
class JoinTableTagGossip < ApplicationRecord
  belongs_to :tag
  belongs_to :gossip
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  has_many :join_pm_receivers
  has_many :recipients, class_name: "User", through: :join_pm_receivers
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :join_table_tag_gossips
  has_many :gossips, through: :join_table_tag_gossips
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :comments
  has_many :gossips, through: :comment
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
    @current_city = City.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @gossip = Gossip.find(params[:gossip_id])
    @comment = Comment.create(content: params[:content], user_id: User.first.id, gossip_id: @gossip.id)
    @tags = JoinTableTagGossip.all.map{|join| join.gossip_id == @gossip.id ? join.tag.title : nil}.compact    
    if @comment.save 
      @comments = @gossip.comments
      @comment = Comment.new
      render 'gossips/show'
    end
  end
  def edit
    @comment = Comment.new
  end
  def update
    @gossip = Gossip.find(params[:gossip_id])
    @tags = JoinTableTagGossip.all.map{|join| join.gossip_id == @gossip.id ? join.tag.title : nil}.compact    
    @comment = Comment.find(params[:id])
    if @comment.update(content: params[:content])
      @comments = @gossip.comments
      @comment = Comment.new
      render 'gossips/show'
    end
  end
  def destroy
    @gossip = Gossip.find(params[:gossip_id])
    @tags = JoinTableTagGossip.all.map{|join| join.gossip_id == @gossip.id ? join.tag.title : nil}.compact    
    @comment = Comment.find(params[:id])
    if @comment.destroy
      @comments = @gossip.comments
      @comment = Comment.new
      render 'gossips/show'
    end
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def index
  end

  def show
    @gossip = Gossip.find(params[:id])
    @comment = Comment.new
    @tags = JoinTableTagGossip.all.map{|join| join.gossip_id == @gossip.id ? join.tag.title : nil}.compact    
    @comments = @gossip.comments
  end

  def new
    @gossip = Gossip.new
    @tag = JoinTableTagGossip.new
    @tags = Tag.all
  end

  def create
    @tags = Tag.all
    @gossip = Gossip.new(title: params[:title], content: params[:content], user_id: params[:user])
    if @gossip.save && params[:tag] != ""
      @tag = JoinTableTagGossip.create(tag_id: Tag.find(params[:tag]).id, gossip_id: @gossip.id) 
      render :index
    elsif @gossip.save && params[:tag] == ""
      render :index
    else
      render :new
    end
  end

  def edit
    @tags = Tag.all
    @gossip = Gossip.find(params[:id])
  end

  def update
    show
    @tag = JoinTableTagGossip.find_by(gossip_id: @gossip.id)
    if @gossip.update(title: params[:title], content: params[:content])
      if params[:tag] == "" && @tag = nil
        puts params
        render :show
      else 
        @tag != nil ? @tag.update(tag_id: Tag.find(params[:tag]).id, gossip_id: @gossip.id) : JoinTableTagGossip.create(tag_id: Tag.find(params[:tag]).id, gossip_id: @gossip.id) 
        puts params
        show
        render :show
      end
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    if @gossip.destroy
      render :index
    else
      render :show
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contact
  end

  def team
  end

  def create
    user = User.find_by(email: params[:emails])

    # on vérifie si l'utilisateur existe bien ET si on arrive à l'authentifier (méthode bcrypt) avec le mot de passe
    if user && user.authenticate(password: params[:password])
      session[:user_id] = user.id
      # redirige où tu veux, avec un flash ou pas

  else
   flash.now[:danger] = 'Invalid email/password combination'
   render 'new'
    end
  end

  def new

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
  # cherche s'il existe un utilisateur en base avec l’e-mail
  user = User.find_by(email: params[:email])

  # on vérifie si l'utilisateur existe bien ET si on arrive à l'authentifier (méthode bcrypt) avec le mot de passe
    if user && user.authenticate(params[:password])
      log_in(user)
    remember(user)
    redirect_to gossips_path# redirige où tu veux, avec un flash ou pas
    else
      render :new
    end
  end

  def destroy
    user = current_user
    if log_out(user)
      redirect_to gossips_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @current_user = User.find(params[:id])
  end



  def create
    nb = rand(1..10)
    @user_create = User.new(first_name: params[:first_name], last_name: params[:last_name], email: params[:email],  age: params[:age], city_id: nb, password: params[:password], password_confirmation: params[:password_confirmation], description: params[:description])

    if @user_create.save
      log_in(@user_create)
      redirect_to root_path

    else
      render :new
    end

  end

  def new
    @user_create = User.new 

  end

  private
    def log_in(user)
      session[:user_id] = user.id
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
  if session[:user_id]
    # même chose que hier
    current_user = User.find_by(id: session[:user_id])

  # nous allons vérifier s'il y a bien un cookie contenant l'id de notre utilisateur
  elsif cookies[:user_id]

    # nous allons trouver l'utilisateur en DB à partir du cookie qui stocke le user_id
    user = User.find_by(id: cookies[:user_id])

    if user

      # nous allons prendre le remember_token stocké en cookie, le hasher, puis le comparer avec notre remember_digest stocké en base
      remember_token = cookies[:remember_token]
      remember_digest = user.remember_digest
      user_authenticated = BCrypt::Password.new(remember_digest).is_password?(remember_token)

      # si tout est bon, il ne nous reste plus qu'à souhaiter bienvenue à l'utilisateur !
      if user_authenticated
        log_in user
        current_user = user
      end

    end
  end
end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/show.html.erb
  <h1><%= @current_city.name %></h1>

<main class="container">
  <h3>Les autres potins de la ville</h3>
  <div class="row row-cols-5 d-flex justify-content-center">
    <% Gossip.all.each do |gossip| %>
      <% if gossip.user.city_id == @current_city.id %>
        <div class="card border-info text-center bg-light my-3 mx-3" style="max-width: 18rem;"> 
          <div class="card-body">
            <h5 class="card-title"><%= gossip.user.first_name %></h5>
            <p class="card-text"><%= gossip.title %></p>
          </div>
          <div class="card-footer">
            <%= link_to "Voir plus", gossip_path(gossip.id), class:"btn btn-outline-info" %>
            <%= link_to "Editer", edit_gossip_path(gossip.id), class:"btn btn-outline-success" %>
            <%= link_to "Supprimer", gossip_path(gossip.id), class:"btn btn-outline-danger", data:{confirm:"Etes vous sûr de vouloir supprimer ce potin ?", method:"DELETE"} %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</main>

app/views/comments/_index.html.erb
<div>
  <% @comments.sort_by(&:created_at).each do |comment| %>
    <p>
      <%= comment.content %>
      <strong><%= comment.user.first_name + " " + comment.user.last_name %></strong>
      <%= link_to "Editer", edit_gossip_comment_path(@gossip.id, comment.id), class:"btn btn-outline-success" %>
      <%= link_to "Supprimer", gossip_comment_path(@gossip.id, comment.id), class:"btn btn-outline-danger", data:{confirm:"Etes vous sûr de vouloir supprimer ce potin ?", method:"DELETE"} %>
    </p>
    <% end %>
</div>

app/views/comments/_new.html.erb
<div class="container mt-5 form-group">
 <%= form_tag gossip_comments_path(@gossip), method: "post" do %>
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

      <%= label_tag 'Commentaire' %>
      <%= text_field_tag 'content', @comment.content, class:"form-control" %>
      <br /> <br />

      <%= submit_tag "Commenter", class:"btn btn-primary"%>

    <% end %>
</div>

app/views/comments/edit.html.erb
<% if @comment.errors.any? %>
    <% @comment.errors.full_messages.each do |message| %>
      <p class="alert alert-danger d-flex justify-content-center" role="alert"><%= message %></p>
    <% end %>
<% end %>

<div class="container mt-5 form-group">
 <%= form_tag url_for(action: 'update'), method: "patch" do %>
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

      <%= label_tag 'Contenu du commentaire' %>
      <%= text_area_tag 'content', @comment.content, class:"form-control" %>
      <br /> <br />

      <%= submit_tag "Editer le commentaire", class:"btn btn-primary"%>

    <% end %>
    <div style="margin-top: 20px;"><%= link_to "Retour Accueil", root_path, :class => "btn btn-info" %></div>
</div>

app/views/gossips/edit.html.erb
<% if @gossip.errors.any? %>
    <% @gossip.errors.full_messages.each do |message| %>
      <p class="alert alert-danger d-flex justify-content-center" role="alert"><%= message %></p>
    <% end %>
<% end %>

<div class="container mt-5 form-group">
 <%= form_tag url_for(action: 'update'), method: "patch" do %>
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

      <%= label_tag 'Titre du potin' %>
      <%= text_field_tag 'title', @gossip.title, class:"form-control" %>
      <br /> <br />

      <%= label_tag 'Contenu du potin' %>
      <%= text_area_tag 'content', @gossip.content, class:"form-control" %>
      <br /> <br />

      <%=select_tag "tag", options_from_collection_for_select(@tags, :id, :title), include_blank: true%>
      <br /> <br />

      <%= submit_tag "Editer le potin", class:"btn btn-primary"%>

    <% end %>
    <div style="margin-top: 20px;"><%= link_to "Retour Accueil", root_path, :class => "btn btn-info" %></div>
</div>

app/views/gossips/index.html.erb
  <div>
    <%if params[:first_name] == nil%>
      <h1>Bienvenue cher Visiteur</h1>
    <%else%>
      <h1>Bienvenue <%= params[:first_name] %></h1>
    <% end %>
  </div>

<% if params[:action] == "create" %>
  <div class="container alert alert-success d-flex justify-content-center alert-dismissible fade show" role="alert">The super potin was succesfully saved !
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% elsif params[:action] == "destroy" %>
  <div class="container alert alert-success d-flex justify-content-center alert-dismissible fade show" role="alert">The shitty potin was motherfucking deleted !
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

  <div class="container d-flex justify-content-center" style="margin-bottom: 20px; margin-top: 20px;"><%= link_to "Nouveau potin", new_gossip_path, :class => "btn btn-info" %></div>

<main class="container">
  <h3>Voici la liste des potins les plus croustillants du web :</h3>
  <p>Cliquez sur le potin de votre choix pour en savoir plus ;)</p>
  <div class="row row-cols-5 d-flex justify-content-center">
    <% Gossip.all.sort.each do |gossip| %>
      <div class="card border-info text-center bg-light my-3 mx-3" style="max-width: 18rem;"> 
        <div class="card-body">
          <h5 class="card-title"><%= gossip.user.first_name %></h5>
          <p class="card-text"><%= gossip.title %></p>
        </div>
        <div class="card-footer">
          <%= link_to "Voir plus", gossip_path(gossip.id), class:"btn btn-outline-info mx-1 my-1" %>
          <%= link_to "Editer", edit_gossip_path(gossip.id), class:"btn btn-outline-success mx-1 my-1" %>
          <%= link_to "Supprimer", gossip_path(gossip.id), class:"btn btn-outline-danger mx-1 my-1", data:{confirm:"Etes vous sûr de vouloir supprimer ce potin ?", method:"DELETE"} %>
        </div>
      </div>
    <% end %>
  </div>
</main>

app/views/gossips/new.html.erb
<% if @gossip.errors.any? %>
    <% @gossip.errors.full_messages.each do |message| %>
      <div class="container alert alert-danger d-flex justify-content-center alert-dismissible fade show" role="alert"><%= message %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
<% end %>

<div class="container mt-5 form-group">
 <%= form_tag url_for(action: 'create'), method: "post" do %>
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

      <%= label_tag 'Titre du potin' %>
      <%= text_field_tag 'title', @gossip.title, class:"form-control" %>
      <br /> <br />

      <%= label_tag 'Contenu du potin' %>
      <%= text_area_tag 'content', @gossip.content, class:"form-control" %>
      <br /> <br />


      <%=select_tag "tag", options_from_collection_for_select(@tags, :id, :title), include_blank: true%>
      <br /> <br />

     <input type="hidden" name="user" value=<%= User.first.id %>>

      <%= submit_tag "Create Post", class:"btn btn-primary"%>

    <% end %>
</div>

app/views/gossips/show.html.erb
<% if params[:action] == "update" %>
  <div class="container alert alert-success d-flex justify-content-center alert-dismissible fade show" role="alert">The super potin was succesfully edited !
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<h1>Vous êtes sur le potin <br>de <%= @gossip.user.first_name %> <%= @gossip.user.last_name %></h1>


<main class="container">
<div style="margin-bottom: 20px;">
  <%= link_to "Editer", edit_gossip_path(@gossip.id), class:"btn btn-outline-success" %>
  <%= link_to "Supprimer", gossip_path(@gossip.id), class:"btn btn-outline-danger", data:{confirm:"Etes vous sûr de vouloir supprimer ce potin ?", method:"DELETE"} %>
</div>
<div class="card">
  <div class="card-header">
    <%= @gossip.title %>
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p><%= @gossip.content %></p>
      <footer class="blockquote-footer"><%= link_to "#{@gossip.user.first_name} #{@gossip.user.last_name}", user_path(@gossip.user.id) %> à <%= link_to "#{@gossip.user.city.name}", city_path(@gossip.user.city.id) %></footer>
    </blockquote>
  </div>
</div>
<div style="margin-top: 20px;"><%= link_to "Retour Accueil", root_path, :class => "btn btn-info" %></div>
<hr>

<h2>Tags</h2>
<% @tags.each do |tag| %>
  <%=tag%>
<% end %>

<h2>Commentaires</h2>

<div>
  <%= render 'comments/index'%>
  <%= render 'comments/new'%>
</div>
</main>

app/views/users/new.html.erb
<div class="container mt-5 form-group">
 <%= form_tag url_for(action: 'create'), method: "post" do %>

      <%= label_tag 'Prénom' %>
      <%= text_field_tag 'first_name', @user_create.first_name, class:"form-control" %>
      <br /> <br />

			<%= label_tag 'Nom' %>
      <%= text_field_tag 'last_name', @user_create.last_name, class:"form-control" %>
      <br /> <br />

			<%= label_tag 'Âge' %>
      <%= number_field_tag 'age', @user_create.age, class:"form-control" %>
      <br /> <br />

			<%= label_tag 'Description' %>
			<%= text_area_tag 'description', @user_create.description, class:"form-control" %>
			<br /> <br />

			<%= label_tag 'Email' %>
      <%= text_field_tag 'email', @user_create.email, class:"form-control" %>
      <br /> <br />

			<%= label_tag 'Mot de passe' %>
      <%= password_field_tag 'password', class:"form-control" %>
      <br /> <br />

			<%= label_tag 'Confirmation du mot de passe' %>
      <%= password_field_tag 'password_confirmation', class:"form-control" %>
      <br /> <br />

      <%= submit_tag "S'inscrire", class:"btn btn-primary"%>

    <% end %>
</div>

app/views/users/show.html.erb
  <h1>Profil de <%= @current_user.first_name %> <%= @current_user.last_name %></h1>

<main class="container">
<div class="card" >
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Description : <%= @current_user.description %></li>
    <li class="list-group-item">Email : <%= @current_user.email %></li>
    <li class="list-group-item">Age : <%= @current_user.age %></li>
    <li class="list-group-item">Ville : <%= link_to "#{@current_user.city.name}", city_path(@current_user.city.id) %></li>
  </ul>
</div>

  <h3>Les autres potins de l'auteur</h3>
  <div class="row row-cols-5 d-flex justify-content-center">
    <% Gossip.all.each do |gossip| %>
      <% if gossip.user_id == @current_user.id %>
        <div class="card border-info text-center bg-light my-3 mx-3" style="max-width: 18rem;"> 
          <div class="card-body">
            <h5 class="card-title"><%= gossip.user.first_name %></h5>
            <p class="card-text"><%= gossip.title %></p>
          </div>
          <div class="card-footer">
            <%= link_to "Voir plus", gossip_path(gossip.id), class:"btn btn-outline-info" %>
            <%= link_to "Editer", edit_gossip_path(gossip.id), class:"btn btn-outline-success" %>
            <%= link_to "Supprimer", gossip_path(gossip.id), class:"btn btn-outline-danger", data:{confirm:"Etes vous sûr de vouloir supprimer ce potin ?", method:"DELETE"} %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</main>