config/routes.rb
Rails.application.routes.draw do
  #home
  root to: 'gossips#index'

  #pages menu
  get '/team', to: 'pages#team'
  get '/contact', to: 'pages#contact'
  get '/register', to: 'pages#create'
  #gossips
  resources :gossips do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  #users
  resources:users

  #cities
  resources:cities, only: [:show]

  #session
  resources:sessions


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users 
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title,
    presence: true,
    length: { minimum: 3, too_short: "%{count} characters is the minimum allowed", maximum: 14, too_long: "%{count} characters is the maximum allowed" }
  validates :content,
    presence: true
  belongs_to :user
  has_many :join_table_tag_gossips
  has_many :tags, through: :join_table_tag_gossips
  has_many :comments
  has_many :users, through: :comments
end

app/models/join_pm_receiver.rb
class JoinPmReceiver < ApplicationRecord
  belongs_to :private_message
  belongs_to :recipient, class_name: "User"
end

app/models/join_table_tag_gossip.rb
class JoinTableTagGossip < ApplicationRecord
  belongs_to :tag
  belongs_to :gossip
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  has_many :join_pm_receivers
  has_many :recipients, class_name: "User", through: :join_pm_receivers
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :join_table_tag_gossips
  has_many :gossips, through: :join_table_tag_gossips
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :comments
  has_many :gossips, through: :comment
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
    @current_city = City.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contact
  end

  def team
  end

  def create
    user = User.find_by(email: params[:emails])

    # on vérifie si l'utilisateur existe bien ET si on arrive à l'authentifier (méthode bcrypt) avec le mot de passe
    if user && user.authenticate(password: params[:password])
      session[:user_id] = user.id
      # redirige où tu veux, avec un flash ou pas

  else
   flash.now[:danger] = 'Invalid email/password combination'
   render 'new'
    end
  end

  def new

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @current_user = User.find(params[:id])
  end



  def create
    nb = rand(1..10)
    @user_create = User.new(first_name: params[:first_name], last_name: params[:last_name], email: params[:email],  age: params[:age], city_id: nb, password: params[:password], password_confirmation: params[:password_confirmation], description: params[:description])

    if @user_create.save
      log_in(@user_create)
      redirect_to root_path

    else
      render :new
    end

  end

  def new
    @user_create = User.new 

  end

  private
    def log_in(user)
      session[:user_id] = user.id
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
  if session[:user_id]
    # même chose que hier
    current_user = User.find_by(id: session[:user_id])

  # nous allons vérifier s'il y a bien un cookie contenant l'id de notre utilisateur
  elsif cookies[:user_id]

    # nous allons trouver l'utilisateur en DB à partir du cookie qui stocke le user_id
    user = User.find_by(id: cookies[:user_id])

    if user

      # nous allons prendre le remember_token stocké en cookie, le hasher, puis le comparer avec notre remember_digest stocké en base
      remember_token = cookies[:remember_token]
      remember_digest = user.remember_digest
      user_authenticated = BCrypt::Password.new(remember_digest).is_password?(remember_token)

      # si tout est bon, il ne nous reste plus qu'à souhaiter bienvenue à l'utilisateur !
      if user_authenticated
        log_in user
        current_user = user
      end

    end
  end
end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Gossip Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>

  <body>
  <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
      <%= link_to "The Gossip Project", root_path, :class => "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav">
          <li class="nav-item <%= 'active' if current_page?(root_path) %>">
            <%= link_to "Accueil", root_path, :class => "nav-link" %>
          </li>
          <li class="nav-item <%= 'active' if current_page?(team_path) %>">
            <%= link_to "Team", team_path, :class => "nav-link" %>
          </li>
          <li class="nav-item <%= 'active' if current_page?(contact_path) %>">
            <%= link_to "Contact", contact_path, :class => "nav-link" %>
          </li>
          <% if current_user %>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Mes options
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" <%= link_to "Mon profil", user_path(session[:user_id]) %></a>
                  <a class="dropdown-item" <%= link_to "Deconnexion", session_path(session.id), method: :delete %></a>
                </div>
              </li>
              <% else %>
              <li class="nav-item active">
                <a class="nav-link" <%= link_to "Connexion", new_session_path %></a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" <%= link_to "S'inscrire", new_user_path %></a>
              </li>
              <% end %>
        </ul>
      </div>
    </nav>
    <header class="container ">
      <%= link_to root_path do %>
        <%= image_tag "/images/banner.png" %>
      <% end %>
    </header>

    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/contact.html.erb
  <h1>
    Contact : Luca Montaigut
  </h1>

<main class="container">
  <h2>Vous pouvez me contacter sur : </h2>
  <ul>
    <li><a href="mailto:lmontaigut@gmail.com">lmontaigut@gmail.com</a></li> 
    <li> 06.73.82.53.32 </li> 
    <li><a href="https://github.com/luca-montaigut">https://github.com/luca-montaigut</a></li> 
  </ul>
</main>

app/views/pages/register.html.erb
<h1>TEST</h1>

app/views/pages/team.html.erb
<main class="container my-5" style="margin-top : 20px;">
  <div class="card-deck">
    <div class="card text-center bg-light my-3 mx-3" style="border:none; text-align:right;">
      <img id="bibi" class="card-img-top rounded-circle" src="/images/profil.jpeg" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title">Luca Montaigut</h5>
        <p class="card-text">Developpeur débutant chez THP</p>
      </div>
    </div>

    <div class="card text-center bg-light my-3 mx-3" style="border:none;">
      <img id="alfred" class="card-img-top rounded-circle" src="/images/alfred.jpg" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title">Alfred</h5>
        <p class="card-text">Mon fidèle poisson combattant, assistant quotidien et soutien sans faille dans la galère.</p>
      </div>
    </div>
  </div>
</main>
<footer id="lazyrabbit">
  <div>
    <p>  (\(\</p>
    <p>  ( -.-)</p>
    <p>  o_(")(")</p>
  </div>  
</footer>